import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from "next/font/google";

import getCurrentUser from "@/actions/getCurrentUser";
import { ThemeProvider } from "@/providers/theme-provider";
import { Toaster } from "@/components/ui/toaster";
import Navbar from "@/components/navbar/navbar";
import ClientOnly from "@/components/ClientOnly";
import AuthContext from "./context/AuthContext";
import ModalProvider from "@/providers/modal-provider";
import ToastProvider from "@/providers/toast-provider";

const PoppinsFont = Poppins({
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const currentUser = await getCurrentUser();

  return (
    <html lang="es">
      <body className={PoppinsFont.className}>
        <AuthContext>
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
            <ClientOnly>
              <ToastProvider />
              <Toaster />
              <ModalProvider />
            </ClientOnly>
            <Navbar currentUser={currentUser} />
            {children}
          </ThemeProvider>
        </AuthContext>
      </body>
    </html>
  );
}
